### ISSUE TITLE
formatting in QgsLayoutItemMapOverview

### ISSUE THREAD

**Issue by 3nids** [qgis/pyqgis#17] opened 2018-05-24 12:05 UTC
Paragraphs are wrongly formed (split, indentation) in the upper part of the QgsLayoutItemMapOverview class
Also, the "see also" frame is merged with the Methods one.

https://qgis.org/pyqgis/master/core/Layout/QgsLayoutItemMapOverview.html

**Comment by DelazJ** [comment] 2018-05-24 12:10
@3nids I didn't know about this repo. Sorry for the mistake.
I wonder if the first paragraph of this issue is not a duplicate of #14

**Comment by 3nids** [comment] 2018-05-24 12:19
no worries, I'll have a look asap

**Comment by nyalldawson** [comment] 2018-08-21 20:37
Fixed in latest version

**Closed by nyalldawson** 2018-08-21 20:37 UTC
