### ISSUE TITLE
Add overflow wrap in tables for Methods and Signals description

### ISSUE THREAD

**Issue by jfbourdon** [qgis/pyqgis#67] opened 2021-02-23 15:47 UTC
Currently, all tables displaying Methods and Signals have a max width of 800px which often forces the user to scroll horizontally to read all the content of a cell. I think it would be more user friendly (and elegant) if the cells had instead an overflow wrap. The max width could stay at 800px, but could also very well be unrestricted, the width being responsive anyway. I tried to find myself in the repo where the change could be made but I'm at a complete loss! I suppose the template with all the CSS/HTML is elsewhere...

**Comment by 3nids** [comment] 2021-05-26 09:45
The table is generated by a home-made autoautosummary: https://github.com/qgis/pyqgis/blob/master/autoautosummary.py
The RST template using this table is: https://github.com/qgis/pyqgis/blob/master/rst/qgis_pydoc_template.txt
And finally, we use the read-the-docs theme: https://sphinx-rtd-theme.readthedocs.io/en/stable/

I guess this would be done by customizin the RTD theme's CSS?

**Comment by 3nids** [comment] 2021-05-26 09:47
duplicate of #36

**Closed by 3nids** 2021-05-26 09:47 UTC
